# OASIS INFOBYTE INTERNSHIP
# Task_NO-4. EMAIL SPAM DETECTION¶
# NAME - DIPANJAN MAHATA
# INTERNSHIP - DATA SCIENCE

In [1]:
# import all libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\ASUS\anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
mail=pd.read_csv("spam.csv",encoding="latin1")
mail

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
mail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [6]:
mail.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [7]:
mail.describe()

v1                      v2  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

#  Data Preprocessing

In [9]:
del mail['Unnamed: 2']
del mail['Unnamed: 3']
del mail['Unnamed: 4']

In [10]:
mail.rename(columns={'v1':'category','v2':'Message'},inplace=True)

In [11]:
spam=mail.groupby('category')['Message'].count()
spam

category
ham     4825
spam     747
Name: Message, dtype: int64

In [13]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
mail['spam']=label_encoder.fit_transform(mail['category'])
mail.head()

category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

# Feature selection

In [14]:
x=mail['Message']
y=mail['spam']

# Data splitting

In [15]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=40)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
C=CountVectorizer()

In [18]:
#here we will convert Email into number matrix

train_x_Count=C.fit_transform(x.values)
train_x_Count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Model selection and implimentation

In [19]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

# Model training

In [24]:
model.fit(train_x_Count,y)

#  Model evaluations

In [26]:
emails=['Hey Dipanjan,can we go to shopping tomorrow?','Upto 50% discount on each top,exclusive offer.we should not miss this reward!']
emails_Count=C.transform(emails)
model.predict(emails_Count)

array([0, 1])

In [27]:
test_x_Count=C.transform(test_x)
model.predict(test_x_Count)

array([0, 1, 0, ..., 0, 1, 0])

In [28]:
model.score(test_x_Count,test_y)

0.9952153110047847

In [29]:
pr=model.predict(test_x_Count)

In [30]:
from sklearn.metrics import confusion_matrix,classification_report

cm=confusion_matrix(test_y,pr)
cm

array([[1455,    2],
       [   6,  209]], dtype=int64)

In [31]:
from sklearn.pipeline import Pipeline

clf = Pipeline([('Vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [32]:
clf.fit(train_x,train_y)

Pipeline(steps=[('Vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [33]:
clf.score(test_x,test_y)

0.986244019138756

In [34]:
pr2=clf.predict(test_x)

In [35]:
cm2=confusion_matrix(test_y,pr2)
cm2

array([[1451,    6],
       [  17,  198]], dtype=int64)